### PR TITLE
Fixes to PR #12

### PR DESCRIPTION
**Pull request by escherstair**
Fixes to [PR #12](https://github.com/STMicroelectronics/iis3dwb-pid/pull/12)

### CODE REVIEW

**Comment by escherstair** [comment]
@avisconti can you review this PR, please?

**Review by avisconti — CHANGES_REQUESTED** [review]
Thanks for the fix. They LGTM
But I kindly ask you to change the commit header as I requested also previously, with header, a body and a footer. The footer is basically your signature.
Thanks again

**Comment by escherstair** [comment]
> Thanks for the fix. They LGTM But I kindly ask you to change the commit header as I requested also previously, with header, a body and a footer. The footer is basically your signature. Thanks again

done

**Comment by avisconti** [comment]
> > Thanks for the fix. They LGTM But I kindly ask you to change the commit header as I requested also previously, with header, a body and a footer. The footer is basically your signature. Thanks again
> 
> done

But the two previous commits should be deleted, right? Now PR has 3 commits instead of only one

**Comment by escherstair** [comment]
squashed

**Review by avisconti — APPROVED** [review]

**Pull request merged**
